springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 49153

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

custom:
  activeprofileName: production
